### ISSUE TITLE
[NodeJS book]: ch-10: Detecting memory leaks

### ISSUE THREAD

**Issue by wakidurrahman** [wakidurrahman/advanced-node-js#133]
Detecting memory leaks

**Comment by hadoan** [comment]
Hey folks — ran into a similar memory issue recently.

I’m working on a free tool that helps analyze heap snapshots (Node, Python, .NET, etc.) and spot leaks like this one.

Just wanted to share in case it’s helpful for others debugging similar problems.

Happy to chat or give early access if anyone’s interested!
